from linua_updater.constants import SIZE_ESTIMATES


class DLCDatabase:
    def __init__(self):
        self.dlc = {
            "EP01": {"name": "Get to Work", "url": "https://penis.nicole-popova66.workers.dev/EP01.zip"},
            "EP02": {"name": "Get Together", "url": "https://penis.nicole-popova66.workers.dev/EP02.zip"},
            "EP03": {"name": "City Living", "url": "https://penis.nicole-popova66.workers.dev/EP03.zip"},
            "EP04": {"name": "Cats and Dogs", "url": "https://penis.nicole-popova66.workers.dev/EP04.zip"},
            "EP05": {"name": "Seasons", "url": "https://penis.nicole-popova66.workers.dev/EP05.zip"},
            "EP06": {"name": "Get Famous", "url": "https://penis.nicole-popova66.workers.dev/EP06.zip"},
            "EP07": {"name": "Island Living", "url": "https://penis.nicole-popova66.workers.dev/EP07.zip"},
            "EP08": {"name": "Discover University", "url": "https://penis.nicole-popova66.workers.dev/EP08.zip"},
            "EP09": {"name": "Eco Lifestyle", "url": "https://penis.nicole-popova66.workers.dev/EP09.zip"},
            "EP10": {"name": "Snowy Escape", "url": "https://penis.nicole-popova66.workers.dev/EP10.zip"},
            "EP11": {"name": "Cottage Living", "url": "https://penis.nicole-popova66.workers.dev/EP11.zip"},
            "EP12": {"name": "High School Years", "url": "https://penis.nicole-popova66.workers.dev/EP12.zip"},
            "EP13": {"name": "Growing Together", "url": "https://penis.nicole-popova66.workers.dev/EP13.zip"},
            "EP14": {"name": "Horse Ranch", "url": "https://penis.nicole-popova66.workers.dev/EP14.zip"},
            "EP15": {"name": "For Rent", "url": "https://penis.nicole-popova66.workers.dev/EP15.zip"},
            "EP16": {"name": "The Sims 4 Strangerville", "url": "https://penis.nicole-popova66.workers.dev/EP16.zip"},
            "EP17": {"name": "Realm of Magic", "url": "https://penis.nicole-popova66.workers.dev/EP17.zip"},
            "EP18": {"name": "My Wedding Stories", "url": "https://penis.nicole-popova66.workers.dev/EP18.zip"},
            "EP19": {"name": "Werewolves", "url": "https://penis.nicole-popova66.workers.dev/EP19.zip"},
            "EP20": {"name": "Adventure in the Jungle", "url": "https://penis.nicole-popova66.workers.dev/EP20.zip"},
            "EP21": {"name": "Royalty & Legacy", "url": "https://penis.nicole-popova66.workers.dev/EP21.zip"},
            "FP01": {"name": "Holiday Celebration Pack", "url": "https://penis.nicole-popova66.workers.dev/FP01.zip"},
            "GP01": {"name": "Outdoor Retreat", "url": "https://penis.nicole-popova66.workers.dev/GP01.zip"},
            "GP02": {"name": "Spa Day", "url": "https://penis.nicole-popova66.workers.dev/GP02.zip"},
            "GP03": {"name": "Dine Out", "url": "https://penis.nicole-popova66.workers.dev/GP03.zip"},
            "GP04": {"name": "Vampires", "url": "https://penis.nicole-popova66.workers.dev/GP04.zip"},
            "GP05": {"name": "Parenthood", "url": "https://penis.nicole-popova66.workers.dev/GP05.zip"},
            "GP06": {"name": "Jungle Adventure", "url": "https://penis.nicole-popova66.workers.dev/GP06.zip"},
            "GP07": {"name": "StrangerVille", "url": "https://penis.nicole-popova66.workers.dev/GP07.zip"},
            "GP08": {"name": "Star Wars: Journey to Batuu", "url": "https://penis.nicole-popova66.workers.dev/GP08.zip"},
            "GP09": {"name": "Dream Home Decorator", "url": "https://penis.nicole-popova66.workers.dev/GP09.zip"},
            "GP10": {"name": "My Wedding Stories", "url": "https://penis.nicole-popova66.workers.dev/GP10.zip"},
            "GP11": {"name": "Werewolves", "url": "https://penis.nicole-popova66.workers.dev/GP11.zip"},
            "GP12": {"name": "Oasis Springs Pack", "url": "https://penis.nicole-popova66.workers.dev/GP12.zip"},
            "SP01": {"name": "Luxury Party Stuff", "url": "https://penis.nicole-popova66.workers.dev/SP01.zip"},
            "SP02": {"name": "Perfect Patio Stuff", "url": "https://penis.nicole-popova66.workers.dev/SP02.zip"},
            "SP03": {"name": "Cool Kitchen Stuff", "url": "https://penis.nicole-popova66.workers.dev/SP03.zip"},
            "SP04": {"name": "Spooky Stuff", "url": "https://penis.nicole-popova66.workers.dev/SP04.zip"},
            "SP05": {"name": "Movie Hangout Stuff", "url": "https://penis.nicole-popova66.workers.dev/SP05.zip"},
            "SP06": {"name": "Romantic Garden Stuff", "url": "https://penis.nicole-popova66.workers.dev/SP06.zip"},
            "SP07": {"name": "Kids Room Stuff", "url": "https://penis.nicole-popova66.workers.dev/SP07.zip"},
            "SP08": {"name": "Backyard Stuff", "url": "https://penis.nicole-popova66.workers.dev/SP08.zip"},
            "SP09": {"name": "Vintage Glamour Stuff", "url": "https://penis.nicole-popova66.workers.dev/SP09.zip"},
            "SP10": {"name": "Bowling Night Stuff", "url": "https://penis.nicole-popova66.workers.dev/SP10.zip"},
            "SP11": {"name": "Fitness Stuff", "url": "https://penis.nicole-popova66.workers.dev/SP11.zip"},
            "SP12": {"name": "Toddler Stuff", "url": "https://penis.nicole-popova66.workers.dev/SP12.zip"},
            "SP13": {"name": "Laundry Day Stuff", "url": "https://penis.nicole-popova66.workers.dev/SP13.zip"},
            "SP14": {"name": "My First Pet Stuff", "url": "https://penis.nicole-popova66.workers.dev/SP14.zip"},
            "SP15": {"name": "Moschino Stuff", "url": "https://penis.nicole-popova66.workers.dev/SP15.zip"},
            "SP16": {"name": "Tiny Living Stuff", "url": "https://penis.nicole-popova66.workers.dev/SP16.zip"},
            "SP17": {"name": "Nifty Knitting Stuff", "url": "https://penis.nicole-popova66.workers.dev/SP17.zip"},
            "SP18": {"name": "Paranormal Stuff", "url": "https://penis.nicole-popova66.workers.dev/SP18.zip"},
            "SP20": {"name": "Throwback Fit Kit", "url": "https://penis.nicole-popova66.workers.dev/SP20.zip"},
            "SP21": {"name": "Country Kitchen Kit", "url": "https://penis.nicole-popova66.workers.dev/SP21.zip"},
            "SP22": {"name": "Bust the Dust Kit", "url": "https://penis.nicole-popova66.workers.dev/SP22.zip"},
            "SP23": {"name": "Courtyard Oasis Kit", "url": "https://penis.nicole-popova66.workers.dev/SP23.zip"},
            "SP24": {"name": "Fashion Street Kit", "url": "https://penis.nicole-popova66.workers.dev/SP24.zip"},
            "SP25": {"name": "Industrial Loft Kit", "url": "https://penis.nicole-popova66.workers.dev/SP25.zip"},
            "SP26": {"name": "Incheon Arrivals Kit", "url": "https://penis.nicole-popova66.workers.dev/SP26.zip"},
            "SP28": {"name": "Modern Menswear Kit", "url": "https://penis.nicole-popova66.workers.dev/SP28.zip"},
            "SP29": {"name": "Blooming Rooms Kit", "url": "https://penis.nicole-popova66.workers.dev/SP29.zip"},
            "SP30": {"name": "Carnaval Streetwear Kit", "url": "https://penis.nicole-popova66.workers.dev/SP30.zip"},
            "SP31": {"name": "Decor to the Max Kit", "url": "https://penis.nicole-popova66.workers.dev/SP31.zip"},
            "SP32": {"name": "Moonlight Chic Kit", "url": "https://penis.nicole-popova66.workers.dev/SP32.zip"},
            "SP33": {"name": "Little Campers Kit", "url": "https://penis.nicole-popova66.workers.dev/SP33.zip"},
            "SP34": {"name": "First Fits Kit", "url": "https://penis.nicole-popova66.workers.dev/SP34.zip"},
            "SP35": {"name": "Desert Luxe Kit", "url": "https://penis.nicole-popova66.workers.dev/SP35.zip"},
            "SP36": {"name": "Pastel Pop Kit", "url": "https://penis.nicole-popova66.workers.dev/SP36.zip"},
            "SP37": {"name": "Everyday Clutter Kit", "url": "https://penis.nicole-popova66.workers.dev/SP37.zip"},
            "SP38": {"name": "Simtimates Collection Kit", "url": "https://penis.nicole-popova66.workers.dev/SP38.zip"},
            "SP39": {"name": "Bathroom Clutter Kit", "url": "https://penis.nicole-popova66.workers.dev/SP39.zip"},
            "SP40": {"name": "Greenhouse Haven Kit", "url": "https://penis.nicole-popova66.workers.dev/SP40.zip"},
            "SP41": {"name": "Basement Treasures Kit", "url": "https://penis.nicole-popova66.workers.dev/SP41.zip"},
            "SP42": {"name": "Grunge Revival Kit", "url": "https://penis.nicole-popova66.workers.dev/SP42.zip"},
            "SP43": {"name": "Book Nook Kit", "url": "https://penis.nicole-popova66.workers.dev/SP43.zip"},
            "SP44": {"name": "Poolside Splash Kit", "url": "https://penis.nicole-popova66.workers.dev/SP44.zip"},
            "SP45": {"name": "Modern Luxe Kit", "url": "https://penis.nicole-popova66.workers.dev/SP45.zip"},
            "SP46": {"name": "Culinary Delights Kit", "url": "https://penis.nicole-popova66.workers.dev/SP46.zip"},
            "SP47": {"name": "Little Castle Kit", "url": "https://penis.nicole-popova66.workers.dev/SP47.zip"},
            "SP48": {"name": "Goth Galore Kit", "url": "https://penis.nicole-popova66.workers.dev/SP48.zip"},
            "SP49": {"name": "Sunflower & Daisies Kit", "url": "https://penis.nicole-popova66.workers.dev/SP49.zip"},
            "SP50": {"name": "Fashion Nostalgia Kit", "url": "https://penis.nicole-popova66.workers.dev/SP50.zip"},
            "SP51": {"name": "Party Essentials Kit", "url": "https://penis.nicole-popova66.workers.dev/SP51.zip"},
            "SP52": {"name": "Villa on the Riviera Kit", "url": "https://penis.nicole-popova66.workers.dev/SP52.zip"},
            "SP53": {"name": "Cozy Cafe Kit", "url": "https://penis.nicole-popova66.workers.dev/SP53.zip"},
            "SP54": {"name": "Artist Studio Kit", "url": "https://penis.nicole-popova66.workers.dev/SP54.zip"},
            "SP55": {"name": "Kids Fairytale Kit", "url": "https://penis.nicole-popova66.workers.dev/SP55.zip"},
            "SP56": {"name": "Pyjama Party Kit", "url": "https://penis.nicole-popova66.workers.dev/SP56.zip"},
            "SP57": {"name": "Bella's Kitchen Kit", "url": "https://penis.nicole-popova66.workers.dev/SP57.zip"},
            "SP58": {"name": "Gamer's Delight Kit", "url": "https://penis.nicole-popova66.workers.dev/SP58.zip"},
            "SP59": {"name": "Belle's Beauty Boutique Kit", "url": "https://penis.nicole-popova66.workers.dev/SP59.zip"},
            "SP60": {"name": "Downtown Loft Kit", "url": "https://penis.nicole-popova66.workers.dev/SP60.zip"},
            "SP61": {"name": "Luxurious Living Kit", "url": "https://penis.nicole-popova66.workers.dev/SP61.zip"},
            "SP62": {"name": "Professionalism Kit", "url": "https://penis.nicole-popova66.workers.dev/SP62.zip"},
            "SP63": {"name": "Trendy Bathroom Kit", "url": "https://penis.nicole-popova66.workers.dev/SP63.zip"},
            "SP64": {"name": "Romantic Mood Kit", "url": "https://penis.nicole-popova66.workers.dev/SP64.zip"},
            "SP65": {"name": "DIY Repair Kit", "url": "https://penis.nicole-popova66.workers.dev/SP65.zip"},
            "SP66": {"name": "Golden Years Kit", "url": "https://penis.nicole-popova66.workers.dev/SP66.zip"},
            "SP67": {"name": "Kitchen Utensil Kit", "url": "https://penis.nicole-popova66.workers.dev/SP67.zip"},
            "SP68": {"name": "SP68", "url": "https://penis.nicole-popova66.workers.dev/SP68.zip"},
            "SP69": {"name": "Autumn Looks Kit", "url": "https://penis.nicole-popova66.workers.dev/SP69.zip"},
            "SP70": {"name": "SP70", "url": "https://penis.nicole-popova66.workers.dev/SP70.zip"},
            "SP71": {"name": "Country Living Kit", "url": "https://penis.nicole-popova66.workers.dev/SP71.zip"},
            "SP72": {"name": "Ideal Makeup Kit", "url": "https://penis.nicole-popova66.workers.dev/SP72.zip"},
            "SP73": {"name": "Modern Interior Kit", "url": "https://penis.nicole-popova66.workers.dev/SP73.zip"},
            "SP74": {"name": "From the Garden Kit", "url": "https://penis.nicole-popova66.workers.dev/SP74.zip"},
            "SP76": {"name": "SP76", "url": "https://penis.nicole-popova66.workers.dev/SP76.zip"},
            "SP77": {"name": "SP77", "url": "https://penis.nicole-popova66.workers.dev/SP77.zip"},
            "SP81": {"name": "SP81", "url": "https://penis.nicole-popova66.workers.dev/SP81.zip"},
        }
        for dlc_id, info in self.dlc.items():
            if dlc_id in SIZE_ESTIMATES:
                info['size'] = SIZE_ESTIMATES[dlc_id]

    def all(self):
        return self.dlc

    def get(self, dlc_id):
        return self.dlc.get(dlc_id)